var obj={ "_id" : 1,
    "id" : 1,
    "title" : "模块",
    "nodes" : [
        { "id" : 11,
            "title" : "媒体管理",
            "nodes" : [
                { "id" : 110,
                    "title" : "多类型图综合",
                    "nodes" : [
                        { "id" : 1100,
                            "title" : "图表1-图+表",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "showDataValue" : "['pubID','date','click','ipClick','ipPv','pv','uvClick','uvPv','province','city']",
                            "showDataName" : "['媒体名称','日期','点击','ip点击','ip展示','展示','uv点击','uv展示','省','市']",
                            "groupColumnIndex" : "[0,1]",
                            "tableDOMId" : "table1",
                            "tableDOMWidth" : "12",
                            "maindivDOMId" : "div1",
                            "maindivDOMWidth" : "12",
                            "maindivDOMHeight" : "450",
                            "charttype" : "bigmap",
                            "lengendrange" : "[2,7]",
                            "provinceIndex" : "8",
                            "cityIndex" : "9" },
                        { "id" : 1101,
                            "title" : "pie表1",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "showDataValue" : "['直接访问','邮件营销','联盟广告','视频广告','游戏广告','搜索引擎']",
                            "showDataName" : "['直接访问','邮件营销','联盟广告','视频广告','游戏广告','搜索引擎']",
                            "tableDOMId" : "ttttt",
                            "tableDOMWidth" : "6",
                            "maindivDOMId" : "dpie",
                            "searchUrl" : "/media/piedata",
                            "charttype" : "pie",
                            "dataRange" : "[0,5]",
                            "maindivDOMWidth" : "6",
                            "maindivDOMHeight" : "400" },
                        { "id" : 1102,
                            "title" : "Pie-TimeLine",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "searchUrl" : "/media/piewithtimelinedata",
                            "showDataValue" : "['date','aa','bb']",
                            "showDataName" : "['日期','白天','黑夜']",
                            "tableDOMId" : "pietimetable",
                            "maindivDOMId" : "divtimeline1",
                            "tableDOMWidth" : "12",
                            "maindivDOMWidth" : "12",
                            "maindivDOMHeight" : "300",
                            "charttype" : "pietimeline",
                            "dataRange" : "[1,2]" },
                        { "id" : 1103,
                            "title" : "XY",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "showDataValue" : "['pubID','date','click','ipClick','ipPv','pv','uvClick','uvPv','province','city']",
                            "showDataName" : "['媒体名称','日期','点击','ip点击','ip展示','展示','uv点击','uv展示','省','市']",
                            "groupColumnIndex" : "[0,1]",
                            "tableDOMId" : "bbb",
                            "tableDOMWidth" : "5",
                            "maindivDOMWidth" : "7",
                            "maindivDOMId" : "dxy1",
                            "maindivDOMHeight" : "430",
                            "charttype" : "xycompare",
                            "compareRange" : "[2,7]",
                            "objIdIndex" : "0",
                            "xIndex" : "1",
                            "compareValueSelectDOMId" : "value-select",
                            "searchUrl" : "/media/search" } ],
                    "showtype" : "页面",
                    "href" : "/media/mediastats" },
                { "id" : 111,
                    "title" : "大地图",
                    "nodes" : [
                        { "id" : 1110,
                            "title" : "媒体管理.2.1",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "showDataValue" : "['pubID','date','click','ipClick','ipPv','pv','uvClick','uvPv','province','city']",
                            "showDataName" : "['媒体名称','日期','点击','ip点击','ip展示','展示','uv点击','uv展示','省','市']",
                            "groupColumnIndex" : "[0,1]",
                            "tableDOMId" : "table1",
                            "tableDOMWidth" : "12",
                            "maindivDOMId" : "div1",
                            "maindivDOMWidth" : "12",
                            "maindivDOMHeight" : "450",
                            "charttype" : "bigmap",
                            "lengendrange" : "[2,7]",
                            "provinceIndex" : "8",
                            "cityIndex" : "9" } ],
                    "showtype" : "页面",
                    "href" : "/media/mediastats" },
                { "id" : 112,
                    "title" : "饼图",
                    "nodes" : [
                        { "id" : 1120,
                            "title" : "媒体管理.3.1",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "searchUrl" : "/media/piedata",
                            "showDataValue" : "['直接访问','邮件营销','联盟广告','视频广告','游戏广告','搜索引擎']",
                            "showDataName" : "['直接访问','邮件营销','联盟广告','视频广告','游戏广告','搜索引擎']",
                            "tableDOMId" : "ttttt",
                            "tableDOMWidth" : "12",
                            "maindivDOMId" : "dpie",
                            "maindivDOMWidth" : "12",
                            "maindivDOMHeight" : "400",
                            "charttype" : "pie",
                            "dataRange" : "[0,5]" },
                        { "id" : 1121,
                            "title" : "饼图.2",
                            "nodes" : [] } ],
                    "showtype" : "页面",
                    "href" : "/media/mediastats" },
                { "id" : 113,
                    "title" : "时间线饼图",
                    "nodes" : [
                        { "id" : 1130,
                            "title" : "媒体管理.4.1",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "searchUrl" : "/media/piewithtimelinedata",
                            "showDataValue" : "['date','aa','bb']",
                            "showDataName" : "['日期','白天','黑夜']",
                            "tableDOMId" : "pietimetable",
                            "maindivDOMId" : "divtimeline1",
                            "tableDOMWidth" : "6",
                            "maindivDOMHeight" : "300",
                            "maindivDOMWidth" : "6",
                            "charttype" : "pietimeline",
                            "dataRange" : "[1,2]" } ],
                    "showtype" : "页面",
                    "href" : "/media/mediastats" },
                { "id" : 114,
                    "title" : "时间XY轴对比图",
                    "nodes" : [
                        { "id" : 1140,
                            "title" : "媒体管理.5.1",
                            "nodes" : [],
                            "showtype" : "图表",
                            "host" : "",
                            "searchurl" : "",
                            "searchUrl" : "/media/search",
                            "showDataValue" : "['pubID','date','click','ipClick','ipPv','pv','uvClick','uvPv','province','city']",
                            "showDataName" : "['媒体名称','日期','点击','ip点击','ip展示','展示','uv点击','uv展示','省','市']",
                            "groupColumnIndex" : "[0,1]",
                            "tableDOMId" : "bbb",
                            "tableDOMWidth" : "5",
                            "maindivDOMId" : "dxy1",
                            "maindivDOMWidth" : "7",
                            "maindivDOMHeight" : "430",
                            "charttype" : "xycompare",
                            "compareRange" : "[2,7]",
                            "xIndex" : "1",
                            "compareValueSelectDOMId" : "value-select" } ],
                    "showtype" : "页面",
                    "href" : "/media/mediastats" } ],
            "showtype" : "模块" },
        { "id" : 12,
            "title" : "系统管理",
            "nodes" : [
                { "id" : 120,
                    "title" : "模块.3.1",
                    "nodes" : [] } ],
            "showtype" : "页面",
            "href" : "/media/mediastats" } ] }